# -*- coding: utf-8 -*-
"""mlops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wWzQrPyGrEkdMLTLktk2xh62PDjKlQb8
"""



import pandas as pd

# Load dataset
data = pd.read_csv('train.csv')  # Replace 'train.csv' with your uploaded file's name
print(data.head())

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Drop rows with missing values
data = data.dropna()

# Encode categorical variables
encoder = LabelEncoder()
for column in ['Gender', 'Married', 'Education', 'Self_Employed', 'Property_Area', 'Loan_Status', 'Dependents']:  # Added 'Dependents' here
    data[column] = encoder.fit_transform(data[column])

# Define features (X) and target (y)
X = data.drop(['Loan_ID', 'Loan_Status'], axis=1)
y = data['Loan_Status']

# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Model logged with accuracy:0.8229166666666666")
url="file:///content/mlruns/0/93bc99ae7e1547498d0843894a2104ad/artifacts"
print(url)

